[[redirects]]
  from = "/flamap"
  to = "https://relaxed-salamander-ff6e5b.netlify.app/flamap"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*"